//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatternFileTypePlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PatternFileTypePlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file does not contain any supported patterns..
        /// </summary>
        internal static string EmptyPatternFile {
            get {
                return ResourceManager.GetString("EmptyPatternFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is not a valid pattern..
        /// </summary>
        internal static string InvalidPatternFile {
            get {
                return ResourceManager.GetString("InvalidPatternFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern {0}.
        /// </summary>
        internal static string PatternFormat {
            get {
                return ResourceManager.GetString("PatternFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RLE Compression.
        /// </summary>
        internal static string RLECompression {
            get {
                return ResourceManager.GetString("RLECompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}-bit channels are not supported..
        /// </summary>
        internal static string UnsupportedChannelDepth {
            get {
                return ResourceManager.GetString("UnsupportedChannelDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} color mode patterns are not supported..
        /// </summary>
        internal static string UnsupportedImageTypeFormat {
            get {
                return ResourceManager.GetString("UnsupportedImageTypeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0} is not a supported pattern file version..
        /// </summary>
        internal static string UnsupportedPatternFileVersion {
            get {
                return ResourceManager.GetString("UnsupportedPatternFileVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern version {0}.{1} is not supported..
        /// </summary>
        internal static string UnsupportedPatternRecordSubVersion {
            get {
                return ResourceManager.GetString("UnsupportedPatternRecordSubVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern version {0} is not supported..
        /// </summary>
        internal static string UnsupportedPatternRecordVersion {
            get {
                return ResourceManager.GetString("UnsupportedPatternRecordVersion", resourceCulture);
            }
        }
    }
}
